In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import re

In [2]:
ConCurrent = "Clean_Diagnosis.csv"
Data = pd.read_csv(ConCurrent)
Data

,Patient_ID,Full_Name,AGE,SEX,DOB,Visit_Date,DEPT,Physician,Diagnosis,ICD-10,...,BP,BP_Systolic,BP_Diastolic,Heart_Rate(bpm),Temp(Â°C),BMI,Admission_Type,INSURANCE,Bill_Amount,Outcome
0,PT-0001,John Smith,45,M,1979-03-22,2024-01-11,Er,Dr. Bello,Malaria,A09,...,120/80,120,80,78.0,37.2,24.5,OPD,NHIS,5400.0,Discharged
1,pt0002,Jane Doe,46,F,1985-11-05,2001-10-15,Cardiology,DR. JOHNSON,Hypertension,I10,...,140/95,140,95,88.0,36.8,32.1,Inpatient,Self-pay,NaN,Admitted
2,PT_0003,Chidi Ngozi,61,F,1963-07-15,2025-06-03,Pediatrics,Dr. Garxada,Pneumonia,J10,...,132/88,132,88,NaN,36.5,26.4,Emergency,Reliance,24000.0,Referred
3,pt-0004,Ibrahim Okoro,38,M,2000-12-15,2023-07-21,Orthopedics,Prof. Li,Fracture - radius,S52.5,...,115/75,115,75,64.0,35.0,27.8,OPD,AXA,120.0,NaN
4,PT-0006,Funmi Adebayo,19,F,2005-01-01,2024-02-14,Radiology,Dr. O'Neil,Typhoid,A04.0,...,129/85,129,85,79.0,36.9,22.5,OPD,NHIS,23450.0,Discharged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,P096,NaN,27,F,1996-09-27,2024-08-09,Derm,Dr. Adams,Eczema,L30,...,120/78,120,78,73.0,36.9,22.0,Elective,Aetna,500.0,Discharged
84,P097,Richard Stone,67,M,1956-02-13,2024-03-20,Oncology,Dr. Lee,Prostate cancer,C61,...,162/99,162,99,97.0,38.3,29.9,Urgent,Blue Cross,NaN,Expired
85,P098,Diana Paul,35,F,2000-03-14,1988-06-07,Gyn/Ob,Dr. White,Pregnancy,Z34,...,115/74,115,74,72.0,37.1,23.3,Elective,United Health,600.0,Discharged
86,P099,Bashir Ahmed,46,M,1979-11-11,2024-05-31,Cardiology,Dr. Brown,Hypertension,I10,...,145/93,145,93,90.0,37.7,27.2,Urgent,Medicare,1700.0,Discharged
87,P100,Gloria Davis,42,F,1981-02-22,2024-07-06,Neuro,Dr. Green,Migraine,G43,...,128/83,128,83,82.0,37.3,24.6,Emergency,Cigna,950.0,Discharged

In [5]:
# Data["Bill_Amount"] = Data["Bill_Amount"].str.strip()

# Data["Bill_Amount"] = Data["Bill_Amount"].replace("BlueShield", "Blue Shield")
# Data["Bill_Amount"] = Data["Bill_Amount"].replace("BlueCross", "Blue Cross")
# Data["Bill_Amount"] = Data["Bill_Amount"].replace("UnitedHealth", "United Health")
# Data["Bill_Amount"] = Data["Bill_Amount"].str.strip("Ã¢âÂ¦")
# Data["Bill_Amount"] = Data["Bill_Amount"].str.strip("$")
# Data["Outcome"] = Data["Outcome"].replace(["NA", "n/a", "null", "----", "---", "pending"], np.nan)

# Data["Outcome"] = Data["Outcome"].str.strip("\n")
# Data["Outcome"] = Data["Outcome"].str.strip()
# Data["Outcome"] = Data["Outcome"].str.capitalize()


Data["Visit_Date"] = Data["Visit_Date"].replace(["NA", "n/a", "null", "----", "---", "pending", "??", "not recorded"], np.nan)
Data["Visit_Date"] = Data["Visit_Date"].str.strip()
Data["Visit_Date"] = Data["Visit_Date"].str.replace("/", "-")
# Data["Visit_Date"] = Data["Visit_Date"].str.replace("31-04-1972", "30-04-1972")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Jan", "01")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Feb", "02")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Mar", "03")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Apr", "04")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("May", "05")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Jun", "06")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Jul", "07")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Aug", "08")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Sep", "09")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Oct", "10")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Nov", "11")
Data["Visit_Date"] = Data["Visit_Date"].str.replace("Dec", "12")

Data["Visit_Date"] = Data["Visit_Date"].str.strip()
Data["Visit_Date"].unique()

array(['2024-01-11', nan, '03-06-2025', '07 21, 2023', '14-02-2024',
       '02-05-24', '2025-05-05', '2024-10-09', '2025-03-01', '01-05-2025',
       '23-07-2024', '2025-02-12', '2024-08-18', '03-06-2023',
       '02-02-2025', '2024-04-04', '15-07-2023', '25-06-2024',
       '2024-05-15', '2023-08-30', '05-02-2024', '2025-06-01',
       '02-02-2024', '2023-03-15', '19-04-2025', '2025-07-19',
       '2025-02-11', '2025-03-03', '2023-10-10', '2024-06-11',
       '2025-05-21', '2024-07-07', '2024-04-11', '2024-07-02',
       '2024-05-29', '2024-08-01', '2024-02-14', '2024-05-21',
       '2024-07-25', '2024-03-09', '2024-04-25', '2024-06-05',
       '2024-08-12', '2024-04-03', '2024-05-16', '2024-07-30',
       '2024-05-09', '2024-06-10', '2024-04-14', '2024-07-22',
       '2024-05-18', '2024-08-02', '2024-06-28', '2024-03-11',
       '2024-08-08', '2024-04-22', '2024-05-27', '2024-07-15',
       '2024-06-30', '2024-03-06', '2024-07-12', '2024-05-04',
       '2024-08-05', '2024-06-23', '2024-07-18', '2024-04-30',
       '2024-05-13', '2024-06-08', '2024-08-09', '2024-03-20',
       '1988-06-07', '2024-05-31', '2024-07-06'], dtype=object)

In [13]:
Data.loc[Data["Visit_Date"].isna()]

# pd.to_datetime(Data["DOB"], dayfirst= True, errors ="coerce") #only useful if date are different by / and -
# Data["Bill_Amount"] = Data["Bill_Amount"].astype("Int64")
# Data.loc[Data["DOB"].isna(), "DOB"]
# Data["Temperature"].dtype

,Patient_ID,Full_Name,AGE,SEX,DOB,Visit_Date,DEPT,Physician,Diagnosis,ICD-10,...,BP,BP_Systolic,BP_Diastolic,Heart_Rate(bpm),Temp(Â°C),BMI,Admission_Type,INSURANCE,Bill_Amount,Outcome
1,pt0002,Jane Doe,46,F,1985-11-05,NaN,Cardiology,DR. JOHNSON,Hypertension,I10,...,140/95,140,95,88.0,36.8,32.1,Inpatient,Self-pay,NaN,Admitted
10,PT0014,Hauwa Hassan,36,F,1988-11-11,NaN,Pediatrics,Prof. Li,Dengue,A00,...,142/96,142,96,82.0,36.2,20.5,Day Case,NaN,NaN,Discharged
17,PT-0023,Chris Doe,46,M,2000-10-17,NaN,Er,Dr. Bello,Influenza,J10,...,135/85,135,85,NaN,36.6,23.4,OPD,NHIS,NaN,Follow-up
27,PT-0035,Taylor Ahmed,51,F,1973-07-23,NaN,Cardiology,Dr. Bello,Hypertension,I10,...,138/95,138,95,NaN,36.7,30.5,Inpatient,NaN,NaN,Follow-up
32,PT0042,Sam Ahmed,36,M,1987-04-09,NaN,Er,Dr. Smith,Hypertension,I10,...,137/94,137,94,90.0,38.1,27.8,Emergency,NaN,18400.0,Admitted
37,P047,Beatrice Cole,46,F,1981-01-25,NaN,Orthopedics,Dr. Brown,Broken wrist,S62,...,124/80,124,80,75.0,37.5,23.6,Elective,NaN,400.0,Discharged
40,P051,Laura King,41,F,1982-07-07,NaN,Gyn/Ob,Dr. Adams,Prenatal check,Z34,...,118/77,118,77,76.0,36.2,23.3,Elective,Cigna,600.0,Discharged
47,P059,Yusuf Bello,44,M,1979-07-08,NaN,Neuro,Dr. Green,Epilepsy,G40,...,132/86,132,86,89.0,37.7,26.0,Urgent,Aetna,NaN,Admitted
50,P062,Sara Ibrahim,39,F,1984-03-15,NaN,Derm,Dr. Lee,Acne,L70,...,115/75,115,75,70.0,37.0,23.0,Elective,NaN,300.0,Discharged
55,P068,Chioma Eze,27,F,1996-04-12,NaN,Gyn/Ob,Dr. Green,Prenatal,Z34,...,116/74,116,74,72.0,37.1,23.2,Elective,Blue Shield,500.0,Discharged
57,P070,Fatou Diallo,46,F,1985-11-17,NaN,Derm,Dr. Lee,Eczema,L30,...,121/79,121,79,74.0,36.8,26.4,Elective,Aetna,520.0,Discharged
64,P077,Victor Hugo,48,M,1975-10-10,NaN,Neuro,Dr. White,Seizure,G40,...,140/90,140,90,88.0,37.8,26.4,Urgent,Aetna,1200.0,Admitted
72,P085,NaN,37,F,1986-08-11,NaN,Derm,Dr. Green,Eczema,L30,...,119/77,119,77,74.0,36.9,23.0,Elective,Aetna,540.0,Discharged
77,P090,NaN,38,M,1985-01-30,NaN,Derm,Dr. Green,Rash,L20,...,122/79,122,79,76.0,37.0,23.1,Elective,Aetna,520.0,Discharged
82,P095,Ade Johnson,46,M,1977-08-03,NaN,Cardiology,Dr. Green,Heart failure,I50,...,166/101,166,101,99.0,38.5,30.8,Emergency,Medicare,3500.0,Expired

In [6]:
# Data["DOB"].describe()
Data.loc[[1,10, 17, 27, 32, 37, 40, 47, 50, 55, 57, 64, 72, 77, 82], "Visit_Date"] = ["2001-10-15", "2002-18-04", "2009-11-12", "1999-01-03", "2004-12-02", "2007-10-12", "2000-11-07", "2008-01-07", "2009-02-03", "1999-09-12", "2008-11-11", "2000-06-12", "1997-10-12", "2010-11-09", "2012-03-10"]
# Data["Temperature"].dtype
# Data.loc[Data["Temperature"] > 50, "Temperature"] = ((Data["Temperature"]-32)* 5/9).round(1)
# for i in Data["Temperature"]:
#     if i > 50:
#         Data["Temperature"][i] = (i - 32) *5/9

In [8]:
Data["Visit_Date"] = Data["Visit_Date"].replace("07 21, 2023", "21-07-2023")
Data["Visit_Date"] = Data["Visit_Date"].replace("02-05-24", "02-05-2024")
Data["Visit_Date"] = Data["Visit_Date"].replace("2002-18-04", "2002-04-18")
Data["Visit_Date"].unique()

array(['2024-01-11', '2001-10-15', '03-06-2025', '21-07-2023',
       '14-02-2024', '02-05-2024', '2025-05-05', '2024-10-09',
       '2025-03-01', '01-05-2025', '2002-04-18', '23-07-2024',
       '2025-02-12', '2024-08-18', '03-06-2023', '02-02-2025',
       '2024-04-04', '2009-11-12', '15-07-2023', '25-06-2024',
       '2024-05-15', '2023-08-30', '05-02-2024', '2025-06-01',
       '02-02-2024', '2023-03-15', '19-04-2025', '1999-01-03',
       '2025-07-19', '2025-02-11', '2025-03-03', '2023-10-10',
       '2004-12-02', '2024-06-11', '2025-05-21', '2024-07-07',
       '2024-04-11', '2007-10-12', '2024-07-02', '2024-05-29',
       '2000-11-07', '2024-08-01', '2024-02-14', '2024-05-21',
       '2024-07-25', '2024-03-09', '2024-04-25', '2008-01-07',
       '2024-06-05', '2024-08-12', '2009-02-03', '2024-04-03',
       '2024-05-16', '2024-07-30', '1999-09-12', '2024-05-09',
       '2008-11-11', '2024-06-10', '2024-04-14', '2024-07-22',
       '2024-05-18', '2024-08-02', '2024-06-28', '2000-06-12',
       '2024-03-11', '2024-08-08', '2024-04-22', '2024-05-27',
       '2024-07-15', '2024-06-30', '2024-03-06', '1997-10-12',
       '2024-07-12', '2024-05-04', '2024-08-05', '2024-06-23',
       '2010-11-09', '2024-07-18', '2024-04-30', '2024-05-13',
       '2024-06-08', '2012-03-10', '2024-08-09', '2024-03-20',
       '1988-06-07', '2024-05-31', '2024-07-06'], dtype=object)

In [10]:
# Data.loc[[1,4,5,6,7, ], "DOB"]  = ["1985-11-05", ""]

# Data = Data.rename(columns = {"Temperature": "Temp(Â°C)"})
for i in Data["Visit_Date"].dropna():
    if "-" != i[4]:
         lists = i.split("-")
         year = lists[2]
         day = lists[0]
         month = lists[1]

         Data.loc[Data["Visit_Date"] == i, "Visit_Date"]  = f"{year}-{month}-{day}"

#a cleaner way to have done this would have been to create a condition
# inspect = (Data["DOB"].notna() & Data["DOB"].str[4]!="-") #condition
# Data.loc[inspect, "DOB"] =Data.loc[inspect, "DOB"].str[::-1]

# Data.head(10)
# Data.to_csv("Clean_Diagnosis.csv", index = False)

In [13]:

Data["Visit_Date"] = pd.to_datetime(Data["Visit_Date"])

In [17]:
Data["Visit_Date"].unique()
# Data["DOB"].isna().sum()
Data.to_csv("Clean_Diagnosis.csv", index=False)